on:
  push:
    branches:
      - main

jobs:
  build:
    name: compile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update system
        run: sudo apt update

      - name: Install SDL2
        run: sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev

      - name: Install Vulkan
        run: sudo apt install -y libvulkan-dev

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Run build script Compatibility
        run: ./build.sh compat

      - name: Upload compat artifact
        uses: actions/upload-artifact@v4
        with:
          name: skillissue-compat
          path: |
            build/x86-64/
            angelscript-docs/
            src/

      - name: Run build script V3
        run: ./build.sh v3

      - name: Upload v3 artifact
        uses: actions/upload-artifact@v4
        with:
          name: skillissue-v3
          path: |
            build/x86-64-v3/
            angelscript-docs/
            src/